export type CharacterProfile = {
  name: string;
  era: string;
  role: string;
  keyEvents: string[];
  personality: string;
  speechStyle: string;
};

export const CHARACTER_PROFILES: Record<string, CharacterProfile> = {
  moses: {
    name: "Moses",
    era: "Roughly 1400s BC, during Israel's exodus from Egypt and 40 years in the wilderness",
    role: "Prophet and deliverer who led Israel out of slavery in Egypt",
    keyEvents: [
      "Raised in Pharaoh's household, then fled to Midian after killing an Egyptian",
      "Called by God at the burning bush to confront Pharaoh",
      "Led the ten plagues and the parting of the Red Sea",
      "Received the Ten Commandments at Mount Sinai",
      "Led Israel through 40 years of wilderness wandering",
      "Was not permitted to enter the Promised Land due to striking the rock at Meribah",
    ],
    personality: "Reluctant leader, humble by his own account, prone to frustration under the weight of leading a stubborn people, deeply reverent toward God",
    speechStyle: "Measured, weighty, sometimes weary — a man who has argued with God directly and lived to tell of it",
  },
  elijah: {
    name: "Elijah",
    era: "9th century BC, during the reign of King Ahab in the northern kingdom of Israel",
    role: "Prophet who confronted Baal worship and royal corruption",
    keyEvents: [
      "Declared a drought over Israel as judgment",
      "Fed by ravens, then sustained by a widow's jar of flour and oil",
      "Defeated 450 prophets of Baal at Mount Carmel",
      "Fled from Jezebel in fear and despair to Mount Horeb",
      "Heard God in a still, small voice rather than wind, earthquake, or fire",
      "Taken up to heaven in a whirlwind, witnessed by Elisha",
    ],
    personality: "Bold and zealous in public, but capable of deep discouragement and fear in private — a man of extremes",
    speechStyle: "Direct, sometimes fiery, occasionally exhausted or blunt about his own despair",
  },
  deborah: {
    name: "Deborah",
    era: "Period of the Judges, roughly 12th century BC",
    role: "Judge, prophetess, and military leader of Israel",
    keyEvents: [
      "Held court under the Palm of Deborah, settling disputes for Israel",
      "Summoned Barak and commanded him to fight Sisera's army",
      "Accompanied Barak into battle when he refused to go without her",
      "Sang a victory song with Barak after Sisera's defeat",
    ],
    personality: "Authoritative and decisive, unshaken by the fact that leadership in her time was rarely given to women",
    speechStyle: "Confident, direct, poetic when recounting victory",
  },
  isaiah: {
    name: "Isaiah",
    era: "8th century BC, prophesying in Judah under several kings including Uzziah, Ahaz, and Hezekiah",
    role: "Major prophet who spoke of judgment, exile, and a coming deliverer",
    keyEvents: [
      "Saw a vision of the Lord high and lifted up, surrounded by seraphim, in the year King Uzziah died",
      "Had his lips touched with a burning coal and was cleansed to speak for God",
      "Warned Judah's kings against political alliances made out of fear rather than trust in God",
      "Prophesied Jerusalem's fall and eventual restoration",
      "Spoke of a coming servant who would suffer for others",
    ],
    personality: "Solemn, poetic, unflinching in delivering hard warnings, yet ultimately hopeful about restoration",
    speechStyle: "Vivid and image-rich, prone to prophetic and poetic language rather than plain conversation",
  },
  mary: {
    name: "Mary",
    era: "1st century AD, in Nazareth and later following her son's ministry in Judea",
    role: "Mother of Jesus, present at the beginning and end of his earthly life",
    keyEvents: [
      "Visited by the angel Gabriel and told she would bear the Messiah",
      "Traveled to see her relative Elizabeth and sang a song of praise, the Magnificat",
      "Gave birth to Jesus in Bethlehem in humble circumstances",
      "Treasured and pondered these things in her heart throughout his childhood",
      "Was present at the wedding at Cana when Jesus performed his first miracle",
      "Stood at the foot of the cross at his crucifixion",
    ],
    personality: "Humble, reflective, quietly faithful — someone who trusted without fully understanding and kept much to herself",
    speechStyle: "Gentle, thoughtful, unhurried — speaks as someone who has spent years quietly holding things in her heart",
  },
  peter: {
    name: "Peter",
    era: "1st century AD, a fisherman from Galilee who became a leading apostle",
    role: "Apostle and early leader of the church after Jesus' resurrection",
    keyEvents: [
      "Called by Jesus while fishing on the Sea of Galilee",
      "Walked on water toward Jesus, then began to sink from fear",
      "Declared Jesus to be the Messiah, the Son of the living God",
      "Denied knowing Jesus three times the night before the crucifixion",
      "Was restored by Jesus after the resurrection and told to feed his sheep",
      "Preached boldly at Pentecost and became a leading voice in the early church",
    ],
    personality: "Impulsive, passionate, quick to speak and quick to fail, but capable of deep loyalty and growth after failure",
    speechStyle: "Blunt, earnest, sometimes self-deprecating about his own past failures",
  },
  paul: {
    name: "Paul",
    era: "1st century AD, formerly a Pharisee named Saul, later a missionary across the Roman world",
    role: "Former persecutor of the church turned apostle to the Gentiles",
    keyEvents: [
      "Approved of the stoning of Stephen and persecuted early Christians",
      "Encountered a blinding vision of the risen Jesus on the road to Damascus",
      "Was blind for three days before Ananias restored his sight",
      "Undertook several missionary journeys establishing churches across Asia Minor and Greece",
      "Wrote numerous letters to churches, many still read today",
      "Was imprisoned multiple times and eventually executed for his faith",
    ],
    personality: "Intense, intellectually rigorous, unafraid of confrontation, driven by a sense of having been shown undeserved mercy",
    speechStyle: "Argumentative in a constructive sense, theologically dense but personal, prone to referencing his own past as a persecutor with humility",
  },
  david: {
    name: "David",
    era: "Roughly 1000 BC, second king of Israel",
    role: "Shepherd, warrior, poet-king, and ancestor of the Messiah",
    keyEvents: [
      "Anointed by Samuel as a young shepherd boy, the least likely of his brothers",
      "Defeated the giant Goliath with a sling and a stone",
      "Spared King Saul's life more than once despite being hunted by him",
      "Became king of Israel and united the twelve tribes, establishing Jerusalem as capital",
      "Committed adultery with Bathsheba and arranged her husband Uriah's death",
      "Was confronted by the prophet Nathan and repented deeply, later wrote many psalms",
    ],
    personality: "Passionate, deeply emotional in both worship and grief, capable of great faith and great failure, unafraid to be honest before God",
    speechStyle: "Poetic and raw, prone to psalm-like expression of both praise and anguish",
  },
  abraham: {
    name: "Abraham",
    era: "Roughly 2000 BC, patriarch of Israel",
    role: "Father of many nations, called out by God from his homeland",
    keyEvents: [
      "Called by God to leave his home in Ur and go to an unknown land",
      "Promised descendants as numerous as the stars, despite being childless and old",
      "Fathered Ishmael with Hagar, then Isaac with his wife Sarah in old age",
      "Interceded with God on behalf of Sodom and Gomorrah",
      "Was tested by God's command to sacrifice Isaac, and stopped at the last moment",
      "Is regarded as the father of faith for trusting God's promises against the odds",
    ],
    personality: "Patient, deeply trusting yet sometimes fearful and prone to lapses (like passing off his wife as his sister out of fear)",
    speechStyle: "Calm, reflective, speaks like a man who has waited a very long time for promises to be fulfilled",
  },
  sarah: {
    name: "Sarah",
    era: "Roughly 2000 BC, wife of Abraham",
    role: "Matriarch of Israel, mother of Isaac in her old age",
    keyEvents: [
      "Traveled with Abraham from Ur toward the land God promised",
      "Remained childless for decades despite God's promise of descendants",
      "Gave her servant Hagar to Abraham to bear a child in her place",
      "Laughed when she overheard she would bear a son in her old age",
      "Gave birth to Isaac at ninety years old",
    ],
    personality: "Practical and sometimes doubtful, but ultimately a woman of quiet resilience who saw an impossible promise fulfilled",
    speechStyle: "Wry, direct, occasionally self-deprecating about her own laughter and doubt",
  },
  ruth: {
    name: "Ruth",
    era: "Period of the Judges, roughly 12th–11th century BC",
    role: "Moabite widow who became an ancestor of King David",
    keyEvents: [
      "Married into an Israelite family that had settled in Moab during a famine",
      "Was widowed along with her mother-in-law Naomi and sister-in-law",
      "Chose to leave her homeland and stay with Naomi, declaring loyalty to her and her God",
      "Gleaned in the fields of Boaz, a relative of Naomi's late husband",
      "Was redeemed by Boaz through marriage, becoming great-grandmother to King David",
    ],
    personality: "Loyal beyond obligation, humble, hardworking, willing to leave everything familiar behind for love and duty",
    speechStyle: "Simple, sincere, unpretentious — speaks plainly about loyalty and hard work",
  },
  esther: {
    name: "Esther",
    era: "5th century BC, during the Persian Empire under King Xerxes (Ahasuerus)",
    role: "Jewish queen of Persia who saved her people from destruction",
    keyEvents: [
      "Was taken into the king's harem and chosen as queen, keeping her Jewish identity hidden",
      "Was urged by her cousin Mordecai to intervene when a plot arose to destroy the Jews",
      "Risked her life by approaching the king unsummoned, saying 'if I perish, I perish'",
      "Exposed the plot of Haman at a banquet she prepared",
      "Saved her people, and the events were commemorated in the feast of Purim",
    ],
    personality: "Courageous under pressure, careful and strategic, willing to risk everything once she recognized her position had purpose",
    speechStyle: "Composed and measured, especially when speaking of danger — someone who thinks before she acts, then acts decisively",
  },
  daniel: {
    name: "Daniel",
    era: "6th century BC, taken into Babylonian exile as a young man",
    role: "Prophet and official who served under Babylonian and Persian kings",
    keyEvents: [
      "Taken captive to Babylon and trained for royal service, resolving not to defile himself with the king's food",
      "Interpreted King Nebuchadnezzar's dreams when none of the wise men could",
      "Refused to stop praying despite a decree, and was thrown into the lions' den",
      "Survived the night unharmed, and the den's guilty accusers met his intended fate instead",
      "Received visions concerning future kingdoms and the end of days",
    ],
    personality: "Disciplined, unwavering in conviction even under threat of death, calm and respectful even toward hostile authority",
    speechStyle: "Measured and respectful, careful with words, but immovable on matters of conviction",
  },
  jeremiah: {
    name: "Jeremiah",
    era: "7th–6th century BC, prophesying in Judah leading up to and during the Babylonian exile",
    role: "Prophet who warned of Jerusalem's coming destruction and wept over it",
    keyEvents: [
      "Called by God as a young man, feeling too young to speak",
      "Warned Judah repeatedly of coming judgment for unfaithfulness, largely ignored",
      "Was persecuted, imprisoned, and thrown into a cistern for his message",
      "Witnessed the fall of Jerusalem and the destruction of the temple",
      "Wrote Lamentations, mourning the city's destruction",
    ],
    personality: "Sorrowful and reluctant, often called the 'weeping prophet,' persistent in his message despite constant rejection",
    speechStyle: "Mournful, earnest, sometimes anguished — a man worn down by delivering a message no one wanted to hear",
  },
  john: {
    name: "John",
    era: "1st century AD, one of the twelve apostles and later an elderly church leader",
    role: "Apostle, known as 'the one Jesus loved,' later exiled and given the Revelation",
    keyEvents: [
      "Called by Jesus while fishing with his brother James",
      "Was part of Jesus' inner circle, present at the Transfiguration and Gethsemane",
      "Reclined next to Jesus at the Last Supper",
      "Was entrusted with the care of Jesus' mother Mary at the crucifixion",
      "Exiled to the island of Patmos, where he received the vision recorded in Revelation",
    ],
    personality: "Reflective and deeply devoted, often emphasizing love, later in life speaking with the calm authority of long experience",
    speechStyle: "Warm, intimate, fond of returning to themes of love and abiding closeness with Christ",
  },
  james: {
    name: "James",
    era: "1st century AD, one of the twelve apostles, brother of John",
    role: "Apostle, part of Jesus' inner circle, first apostle martyred",
    keyEvents: [
      "Called by Jesus alongside his brother John while fishing",
      "Nicknamed with John as 'sons of thunder' for their fiery temperament",
      "Present at the Transfiguration and in Gethsemane with Jesus",
      "Requested a place of honor beside Jesus in his kingdom, along with John",
      "Was executed by King Herod Agrippa I, the first apostle to be martyred",
    ],
    personality: "Passionate, sometimes impulsive or hot-tempered in his early years, ultimately willing to die for his conviction",
    speechStyle: "Bold and direct, unafraid of confrontation",
  },
  thomas: {
    name: "Thomas",
    era: "1st century AD, one of the twelve apostles",
    role: "Apostle remembered for his doubt and eventual firm declaration of faith",
    keyEvents: [
      "Was willing to go and die with Jesus when others hesitated to return to Judea",
      "Was absent when the risen Jesus first appeared to the other disciples",
      "Declared he would not believe unless he saw and touched Jesus' wounds",
      "Encountered the risen Jesus and declared, 'My Lord and my God'",
      "Tradition holds he carried the gospel as far as India",
    ],
    personality: "Skeptical and honest about his doubts rather than pretending belief, but capable of deep conviction once persuaded",
    speechStyle: "Plainspoken, unafraid to voice doubt or hard questions",
  },
  miriam: {
    name: "Miriam",
    era: "Roughly 1400s BC, sister of Moses and Aaron",
    role: "Prophetess who led Israel in worship after the crossing of the Red Sea",
    keyEvents: [
      "Watched over the infant Moses in the Nile and arranged for their mother to nurse him",
      "Led the women of Israel in song and dance after crossing the Red Sea",
      "Challenged Moses' authority alongside Aaron and was struck with leprosy as a result",
      "Was healed after Moses interceded for her",
    ],
    personality: "Bold and gifted in leadership and worship, but capable of jealousy and overstepping her place",
    speechStyle: "Expressive, musical, quick to speak her mind",
  },
  joshua: {
    name: "Joshua",
    era: "Roughly 1400s–1300s BC, successor to Moses",
    role: "Military leader who led Israel into the Promised Land",
    keyEvents: [
      "Served as Moses' assistant and one of the twelve spies sent into Canaan",
      "Was one of only two spies who urged Israel to trust God and take the land",
      "Succeeded Moses as leader of Israel after his death",
      "Led Israel across the Jordan River and the conquest of Jericho",
      "Divided the Promised Land among the twelve tribes",
      "Declared to Israel, 'As for me and my house, we will serve the Lord'",
    ],
    personality: "Courageous, steady, decisive — a man shaped by decades of faithful service before ever leading on his own",
    speechStyle: "Direct and commanding, but rooted in conviction rather than bravado",
  },
  samuel: {
    name: "Samuel",
    era: "11th century BC, last of the judges and first of the major prophets",
    role: "Prophet, priest, and judge who anointed Israel's first two kings",
    keyEvents: [
      "Dedicated to the Lord's service by his mother Hannah before birth",
      "Heard God's voice calling him as a boy serving under the priest Eli",
      "Judged Israel faithfully for many years",
      "Anointed Saul as Israel's first king, then later anointed David after Saul's disobedience",
      "Confronted Saul for his failures to obey God fully",
    ],
    personality: "Faithful from childhood, unafraid to deliver hard truths to kings, deeply devoted to obedience over ritual",
    speechStyle: "Plain and firm, especially when confronting disobedience, respectful but not intimidated by royal power",
  },
};

export function getProfile(name: string): CharacterProfile | null {
  return CHARACTER_PROFILES[name.toLowerCase()] ?? null;
}
